java_binary(
    name = "golink",
    srcs = ["GoLinkHandler.java"],
    main_class = "com.example.GoLinkHandler",
    deps = [
	"@javax_servlet_javax_servlet_api//jar",
        "@org_eclipse_jetty_jetty_http//jar",
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_server//jar",
	"@org_eclipse_jetty_jetty_util//jar",
    ],
)

